### ISSUE TITLE
Getting folder is invalid when trying to select steam folder

### ISSUE THREAD

**Issue by CaffeineCafe** [MarvinXLII/BravelyRandomize2#1]
Trying out the randomizer for steam, but getting the error "The folder is invalid or des not contained the required paks. eg .....Sunrise-E\content\packs"

**Comment by MarvinXLII** [comment]
My computer died this morning so I can't double check things myself at the moment. My guess is you selected the wrong folder. You need to pick a folder that contains Bravely_Default_II-WindowsNoEditor.pak.

**Comment by CaffeineCafe** [comment]
Oh no!
After reviewing the code it seems the system:steam var in the settings.json is commented out. Then more digging lead me to a 2nd build for steam. I will close this and take a look at seeing how this works and how to update the GUI to select version rather than have it hard-coded.
